### ISSUE TITLE
Generate a tag version

### ISSUE THREAD

**Issue by ericmaicon** [rguedes/PDFMerger#1]
Hello there,

I am using this extension and I am grateful that you did it. 

Could you please create a version tag? I would like to avoid use "dev-master" on my composer.json.

Thank you.

**Comment by rguedes** [comment]
Hello @ericmaicon.

Update extension with original repo fixes.

Tag created.

**Comment by ericmaicon** [comment]
I am wondering, did you generate on packagist as well?

**Comment by rguedes** [comment]
No, the package in packagist is not managed by me.
Someone submitted package there..

**Comment by ericmaicon** [comment]
Thank you.
