### ISSUE TITLE
Update FPDF and FPDI

### ISSUE THREAD

**Issue by Seb33300** [rguedes/PDFMerger#2]
Can you please update FPDF and FPDI libraries?

https://github.com/Setasign

The principal issue I have is that FPDI just make a 'die' when an error occurs instead of throwing an exception.
This was solved in the latest FPDI version.

Instead of including them in your repository you may add them to the composer dependency:

```
{
    "require": {
        "setasign/fpdi-fpdf": "1.6.1"
    }
}
```

See: https://github.com/Setasign/FPDI

**Comment by rguedes** [comment]
Thx, I was looking at this.
