### ISSUE TITLE
PDFMerger is not working anymore

### ISSUE THREAD

**Issue by Seb33300** [rguedes/PDFMerger#4]
Since you have updated partially FPDF, PDFMerger is not working anymore.

When testing the sample.php script, multiple PHP errors are shown.

I just create a pull request to make a full update of FPDF and FPDI which solve this issue:
https://github.com/rguedes/PDFMerger/pull/3

**Comment by rguedes** [comment]
Done. Thx

**Comment by Seb33300** [comment]
Can you force packagist to update to the last changes?
https://packagist.org/packages/rguedes/pdfmerger#dev-master
Thanks

**Comment by rguedes** [comment]
No, the package in packagist is not manager by me. Sorry.
