### ISSUE TITLE
Unable to load PDF from URL

### ISSUE THREAD

**Issue by mustafa-taheri** [rguedes/PDFMerger#5]
I am trying to fetch PDF from S3 Bucket. It gives me an error
 **Could not locate PDF on 'https://s3-ap-southeast-1.amazonaws.com/---mypath---.pdf'** Please help. Thanx in advance.

**Comment by mustafa-taheri** [comment]
Any solution to this..??

**Comment by rguedes** [comment]
PDFMerger not allow remote pdf, only local.
You have to download the file and only then use PDFMerge
